### ISSUE TITLE
nothing shows up?

### ISSUE THREAD

**Issue by damian1231** [Prosk8er/Snowstorm-Lights#11]
Do i have to add something to my template files? because nothing shows up when i add this mod and enable it?

http://n7gaming.co.uk/forums/

**Comment by Prosk8er** [comment]
what version of phpbb are you on?
also try to copy phpBB/ext/prosk8er/snowstormlights/styles/prosilver/template/event/ucp_prefs_personal_append.html
to
phpBB/ext/prosk8er/snowstormlights/styles/YOUR STYLE NAME HERE/template/event/ucp_prefs_personal_append.html
and refresh in acp
