### ISSUE TITLE
missing entries in 

### ISSUE THREAD

**Issue by Le-Spirit** [Prosk8er/Snowstorm-Lights#16]
After updating the extension on a phpbb 3.3.9, I was unable to make entries for the new options in the UCP. I had to manually create 3 new rows in the _Users table because the board was spitting error messages:

user_lightscss_enabled, user_snowcss_enabled, user_snowbg_enabled

**Comment by Prosk8er** [comment]
ok thanks i'll take a look at it later

**Comment by Prosk8er** [comment]
did you disable the extension first then remove the old extension, upload new extension, then re-enable it?
i tested a update and fresh install and have no errors everything is working

**Comment by Le-Spirit** [comment]
nope, sorry, I replaced it "live", that's maybe the reason the tables were
not created ?

**Comment by Prosk8er** [comment]
yes you have to do that with every extension otherwise if there is database changes they wont update

**Comment by Le-Spirit** [comment]
Ok, thank you, my bad then.
Otherwise, our members love your work, thank you for it and the (jolly
fast) support you provided !

Have a great 2023.

Le_Spirit

**Comment by Prosk8er** [comment]
no problem have a good new year
