### ISSUE TITLE
Change lights color

### ISSUE THREAD

**Issue by Dacogetul** [Prosk8er/Snowstorm-Lights#17]
How could I change the colors of the lights? Is it enough to change the colors in the images or do I need to change something in the css?

**Comment by Prosk8er** [comment]
if its the smashable ones those are images if your talking about the non smashable ones see https://www.phpbb.com/customise/db/extension/snowstorm_lights/support/topic/243509

**Comment by Dacogetul** [comment]
Thank tou very much !!!
